[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "12.16.2"
  HUGO_VERSION = "0.55.6"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"
